### ISSUE TITLE
Pick one gene between two close gene in distance matrix?

### ISSUE THREAD

**Issue by Vghxv** [BioTechCo/main_project#68]
discussed in discord

**Comment by xzh0623** [comment]
針對這個問題我的看法是可能會出現在不同GO類別(BP、CC、MF)但具有相同功能的GO術語。所以雖然功能相同但類別不同還是會有些許差異，不應直接從中取一個。

**Comment by xzh0623** [comment]
而在距離矩陣的部分，不應直接把相異基因為0的改為1，因為這樣會認為是兩個之間毫無相關，但事實上並非如此。反而比在相同GO類別具有不同功能的情況來的好，所以應該還是要保持原來為0的樣子。

**Comment by Vghxv** [comment]
> 不應直接把相異基因為0的改為1

沒有這樣做過吧

**Comment by Vghxv** [comment]
outdated, closing it
